baseurl = "https://stoneiron.github.io/miosito/"
title = "Pietro Ferraro"
theme = "pulp"
publishDir = "docs"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Pietro Ferraro"
    avatar = "pf.jpg"
    favicon = "favicon.ico"
    description = """
        Laureato in ingegneria informatica e delle telecomunicazioni.
    """
    publicationYear = "2019"
    listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    name = "LinkedIn"
    pre = "<i class='fab fa-linkedin'></i>" #Choose your favorite font from Font Awesome
    url = "https://www.linkedin.com/in/pietro-ferraro-6b7b79b7"
    weight = 10

[[menu.main]]
    name = "Facebook"
    pre = "<i class='fab fa-facebook'></i>"
    url = "https://www.facebook.com/pietroeffe1"
    weight = 20

[[menu.main]]
    name = "Instagram"
    pre = "<i class='fab fa-instagram'></i>"
    url = "https://www.instagram.com/stoneiron"
    weight = 30

[[menu.main]]
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:mail@pietroferraro.it"
    weight = 40
